notifications:
  email: false
sudo: enabled
os: linux
language: python
python: 3.7-dev
cache: pip
env:
  global:
    - GH_REPO=Drakkar-Software/OctoBot-Evaluators
    - DEPLOY_BRANCH=master
    - PACKAGE_FOLDER=octobot_evaluators

install:
  - python3 -m pip install --upgrade --only-binary=Cython Cython
  - python3 -m pip install --upgrade -r dev_requirements.txt
  - python3 -m pip install OctoBot-Commons # TODO remove it
  - python3 -m pip install OctoBot-Channels # TODO remove it
  - python3 -m pip install -r requirements.txt # TODO remove it

matrix:
  include:
    - name: "Linux - Python 3.7-dev - Cython compilation"
      stage: build
      os: linux
      python: 3.7-dev
      language: python
      script:
        - python3 setup.py build_ext --inplace

    - name: "Linux - Python 3.7-dev - Python sources"
      stage: test
      os: linux
      python: 3.7-dev
      language: python
      script:
        - pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests
      after_success:
        - if [ $TRAVIS_PULL_REQUEST == "false" ]; then coveralls; fi

    - name: "Linux - Python 3.7-dev - Installed"
      stage: test
      os: linux
      python: 3.7-dev
      language: python
      script:
        - python3 setup.py install
        - rm -rf $PACKAGE_FOLDER
        - pytest tests

    - name: "Linux - Python 3.7-dev - Deploy"
      stage: deploy
      script:
        - ls
      deploy:
        - provider: pypi
          username:
            secure: f+YjNk1H7XA01PRrnc0vgXBFRDNmOlkM27s2rpmGeNgARTiwVqKyDKmwLkQdZmba71Ew4+BQyqbhPu3hySM+nncM34av/ZkSDJgvp/f0kcvk8htT+IgisJRgwyTHhsKqtWPbGWBcr2mlSJ2iAzJNtgoxnj+v8LIB5rZZvPC0Q6YjwMwBHGfaYwI2eRXtc8RcYXtqqFPyVRLCP10I206PgS4GwPLG6wU+5g3qMzkFOrsTHyjkaM6/GkPrgfoNimY0lPGZqP2qHuthGoT0AdgjNxwGIIn3/G7Jiq4kHMAuxybHmCX9rJWpZwArrJDtbV4WdWbZPmsdDlnd7Cjkh0GEY0luiTK/uQ/axD4KuwzREU8AgcQlDq89hfK3icp9OfRVkHZOoKbt9rpAOef5ea6odMHI9RI9tlXHyXz4LL+YP9rQ2fITGovV6AvcJocLfNSYiWqlYZoYNodkGu4j03hm49FR20rMQlkpfI5JbwTUF7k+/WKGX96Kr/9LF6kRd5FOAFNJdum2r2W8F68d2JsaHZyYQLVfo8Kby8VW1VAUcmv2iTOxP6YZSXYtvr9Zau2KsNQkr8QavQefOR2QzR9jStqXXMx5LovzE5ngLPazTHO30F5hqEqveygtPI9J/wx+tPj1vDk04fXP6zrGUBURfuKebNpt1dlqz9m+3aNdg8I=
          password:
            secure: Dq/LPcdduzDJg5Sw4ToptECcp0JXCl6Zx8vOm8jfXGBX2ccoGMBik3TelvU3aKQIHL8nFLm9t0+QBle4wP8fZyNvfABDITBAYDeof2q1G5jRBu4BSOfk8lRmtQKWApcOSOiWE9tqcrIXHGhoOlj7FabrYBdFXQ9F+zd3XmLHq+JdZM0pOXAq1FkiCvc1iVltLccopyevXgbg4mGpfMl6ojiz5wDWt5eMrQIRnDvKMrvKMMzxgHF3uhUzaxxTRIEJs7sLpRULbwhw87Yt1WL4N5HXLZRIH/Lbx9dDLZ1cbv7a4MNunxLtycgMntJiyVXOePDWEaRsh4Cad4Nct8JItCBiji9Tp0CKX9mGCZnXFe9FicbcMWTuS/Y4Ml+e99jUxg1PZC6z1xenN+xyr6TIuXdE3okxoPMM6UE6V+Qmhb7ds6OcdAmqE5SglQHQaPQtN7ix9pCJ/QbgvSQYMgkT8Si0cRqbfGHRU7Q+zzM55O+X/lzX/85VDmHn+S9bld62Z7bu5axUwEJNfaMFIVxRZjlkHFCHn0NW9mC50BMoFeq5zOLw2kuYnyHk5xVyfaI3Wml6n1FZ4NBZfdXtJwC93K168PXg/qHL4j8UvD+GOMGCfK9Ub/GdERSqCewexBvjup4mqgzeS10HM8+hye/0+jvtLnk178oHdX7vT93d9B4=
          skip_existing: true
          skip_cleanup: true
          distributions: "sdist"
          on:
            repo: $GH_REPO
            branch: $DEPLOY_BRANCH
            tags: true
            condition: $TRAVIS_OS_NAME = 'linux'
