notifications:
  email: false
sudo: enabled
os: linux
language: python
python: 3.7-dev
cache: pip
env:
  global:
    - GH_REPO=Drakkar-Software/OctoBot-Evaluators
    - DEPLOY_BRANCH=master
    - PACKAGE_FOLDER=octobot_evaluators

install:
  - python3 -m pip install --upgrade --only-binary=Cython Cython
  - python3 -m pip install --upgrade -r dev_requirements.txt
  - python3 -m pip install OctoBot-Commons # TODO remove it
  - python3 -m pip install OctoBot-Channels # TODO remove it
  - python3 -m pip install -r requirements.txt # TODO remove it

matrix:
  include:
    - name: "Linux - Python 3.7-dev - Cython compilation"
      stage: build
      os: linux
      python: 3.7-dev
      language: python
      script:
        - python3 setup.py build_ext --inplace

    - name: "Linux - Python 3.7-dev - Python sources"
      stage: test
      os: linux
      python: 3.7-dev
      language: python
      script:
        - pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests
      after_success:
        - if [ $TRAVIS_PULL_REQUEST == "false" ]; then coveralls; fi

    - name: "Linux - Python 3.7-dev - Installed"
      stage: test
      os: linux
      python: 3.7-dev
      language: python
      script:
        - python3 setup.py install
        - rm -rf $PACKAGE_FOLDER
        - pytest tests

    - name: "Linux - Python 3.7-dev - Deploy"
      stage: deploy
      script:
        - ls
      deploy:
        - provider: pypi
          user: "__token__"
          password:
            secure: HHlsEgI/sKI1iG5y571xXlokPZN6nwT4wCeG1oLFX6gEJTMnyWDq8wSiqaaIiOMcs6MWA/pQI6wf4yL0a2lXZMiNQIEC+Q64Iln1leNBXbDDsNYXPHPhsb2ZIPkVf2PFFIUCp+7kNQk7+h/5Px3wmoLs2WZbqy2vMHA4fGKwA3/xrwbjovQTJbDkonyZPzPCo30jsbl5jH/IzH1Lv2hn1xK7yS2w3y+iSV9tj2Wchcfz18OAVrb59PgaQptEzlKqujP6Khj6qV+04cTldzYh2Vd0kyYlSxmSN57EKYVyZfUkXCLm/AcJ55YfNwbrGslmPC/0g8rbmlMVGwB9cHQwBLARu3QwJZ7wW1PDiCXvJ2BTbeihh8dzOneGkgwfOe3HXD1F/7zA0I4NOuucPhcyD+EA3XVzFhNSqCOrK1E9D8pMqxn3c08+ORazdcebVojF7OAODxDOt1cldPwRjjflZ2AV6vOpZZvSKq43A9n3aXDnyTmzJF5y/Q1RjdmAgqb/bCchtUQ3COq5RA7BWtYCWnZURWy3lnjBB99G24v3dR2d1L730mjN72AIqx86bvKYU7YEiwz0ZTzlWaSXUjz78I7oDkYHuQwEnEeQ8AdA78+IJU3/lgac2XuRjkVr4MDwfJm52Y1GrayOC+JvFj9axVA6jgKOfk0WSN0qZwsTim8=
          skip_existing: true
          skip_cleanup: true
          distributions: "sdist"
          on:
            repo: $GH_REPO
            branch: $DEPLOY_BRANCH
            tags: true
            condition: $TRAVIS_OS_NAME = 'linux'
